from __future__ import annotations


CREATED = "CREATED"
GENERATING = "GENERATING"
GENERATED = "GENERATED"
QUALITY_FAILED = "QUALITY_FAILED"
QUALITY_PASSED = "QUALITY_PASSED"
DRAFTING = "DRAFTING"
WP_DRAFTED = "WP_DRAFTED"
APPROVED = "APPROVED"
REJECTED = "REJECTED"
FAILED = "FAILED"

TRANSITIONS = {
    CREATED: {GENERATING, REJECTED},
    GENERATING: {GENERATED, FAILED},
    GENERATED: {QUALITY_PASSED, QUALITY_FAILED, FAILED},
    QUALITY_FAILED: {GENERATING, REJECTED},
    QUALITY_PASSED: {DRAFTING, GENERATING, REJECTED},
    DRAFTING: {WP_DRAFTED, FAILED},
    WP_DRAFTED: {APPROVED, REJECTED},
    APPROVED: set(),
    REJECTED: {GENERATING},
    FAILED: {GENERATING, DRAFTING, REJECTED},
}


def require_transition(current: str, target: str) -> None:
    if target not in TRANSITIONS.get(current, set()):
        raise ValueError(f"unsafe state transition: {current} -> {target}")

