# 23개 사이트 설정
SITES = [
    {
        "url": "https://k-health365.com",
        "theme": "Korean Health & Medical Information",
        "lang": "en",
        "style": "blog",
        "adsense": True,
        "category_id": 964,
        "keywords_file": "kw_health.txt",
        "niche": "health",
    },
    {
        "url": "https://koreamedicaltour.com",
        "theme": "Korea Medical Tourism",
        "lang": "en",
        "style": "blog",
        "adsense": False,
        "category_id": 1,
        "keywords_file": "kw_medicaltour.txt",
        "niche": "medical_tour",
    },
    {
        "url": "https://kskin365.com",
        "theme": "Korean Skincare & Beauty (K-Beauty)",
        "lang": "en",
        "style": "blog",
        "adsense": False,
        "category_id": 1,
        "keywords_file": "kw_skin.txt",
        "niche": "kbeauty",
    },
    {
        "url": "https://korea365.org",
        "theme": "Korea Lifestyle & Culture Guide",
        "lang": "en",
        "style": "blog",
        "adsense": False,
        "category_id": 1,
        "keywords_file": "kw_korea365.txt",
        "niche": "culture",
    },
    {
        "url": "https://jobinkorea365.com",
        "theme": "Jobs in Korea for Foreigners",
        "lang": "en",
        "style": "blog",
        "adsense": False,
        "category_id": 1,
        "keywords_file": "kw_jobinkorea.txt",
        "niche": "jobs",
    },
    {
        "url": "https://jobkorea365.com",
        "theme": "Korea Job Market & Career Guide",
        "lang": "en",
        "style": "blog",
        "adsense": False,
        "category_id": 1,
        "keywords_file": "kw_jobkorea.txt",
        "niche": "jobs",
    },
    {
        "url": "https://jobkoreaglobal.com",
        "theme": "Global Careers in Korea",
        "lang": "en",
        "style": "blog",
        "adsense": False,
        "category_id": 1,
        "keywords_file": "kw_jobglobal.txt",
        "niche": "jobs",
    },
    {
        "url": "https://kstudy365.com",
        "theme": "Study in Korea - University Admissions Guide",
        "lang": "en",
        "style": "blog",
        "adsense": False,
        "category_id": 1,
        "keywords_file": "kw_study.txt",
        "niche": "education",
    },
    {
        "url": "https://studyinkorea.com",
        "theme": "Study in Korea - Student Life & Visas",
        "lang": "en",
        "style": "blog",
        "adsense": False,
        "category_id": 1,
        "keywords_file": "kw_studyinkorea.txt",
        "niche": "education",
    },
    {
        "url": "https://kfinance365.com",
        "theme": "Korean Personal Finance & Investment",
        "lang": "en",
        "style": "blog",
        "adsense": False,
        "category_id": 1,
        "keywords_file": "kw_finance.txt",
        "niche": "finance",
    },
    {
        "url": "https://koreainvest365.com",
        "theme": "Investing in Korea - Stocks & Real Estate",
        "lang": "en",
        "style": "blog",
        "adsense": False,
        "category_id": 1,
        "keywords_file": "kw_invest.txt",
        "niche": "invest",
    },
    {
        "url": "https://koreataxlaw.com",
        "theme": "Korea Tax & Legal Guide for Expats",
        "lang": "en",
        "style": "blog",
        "adsense": False,
        "category_id": 1,
        "keywords_file": "kw_taxlaw.txt",
        "niche": "legal",
    },
    {
        "url": "https://k-trip365.com",
        "theme": "Korea Travel Guide & Itineraries",
        "lang": "en",
        "style": "blog",
        "adsense": False,
        "category_id": 1,
        "keywords_file": "kw_trip.txt",
        "niche": "travel",
    },
    {
        "url": "https://k-visa365.com",
        "theme": "Korea Visa Guide - All Visa Types",
        "lang": "en",
        "style": "blog",
        "adsense": False,
        "category_id": 1,
        "keywords_file": "kw_visa.txt",
        "niche": "visa",
    },
    {
        "url": "https://koreacrypto365.com",
        "theme": "Korea Crypto & Digital Assets",
        "lang": "en",
        "style": "blog",
        "adsense": False,
        "category_id": 1,
        "keywords_file": "kw_crypto.txt",
        "niche": "crypto",
    },
    {
        "url": "https://koreainsurance365.com",
        "theme": "Korea Insurance Guide for Expats & Koreans",
        "lang": "en",
        "style": "blog",
        "adsense": False,
        "category_id": 1,
        "keywords_file": "kw_insurance.txt",
        "niche": "insurance",
    },
    {
        "url": "https://koreanews365.com",
        "theme": "한국 뉴스 & 시사 정보",
        "lang": "ko",
        "style": "news",
        "adsense": False,
        "category_id": 1,
        "keywords_file": "kw_news_ko.txt",
        "niche": "news",
    },
    {
        "url": "https://koreawedding365.com",
        "theme": "Korean Wedding Planning & Culture",
        "lang": "en",
        "style": "blog",
        "adsense": False,
        "category_id": 1,
        "keywords_file": "kw_wedding.txt",
        "niche": "wedding",
    },
    {
        "url": "https://ktech365.com",
        "theme": "Korea Tech & Startup Ecosystem",
        "lang": "en",
        "style": "blog",
        "adsense": False,
        "category_id": 1,
        "keywords_file": "kw_tech.txt",
        "niche": "tech",
    },
    {
        "url": "https://kworld365.com",
        "theme": "Korea Government Benefits & Life Guide",
        "lang": "en",
        "style": "blog",
        "adsense": False,
        "category_id": 1,
        "keywords_file": "kw_world.txt",
        "niche": "lifestyle",
    },
    {
        "url": "https://oliveyoungkorea.com",
        "theme": "Olive Young Korea - K-Beauty Products & Reviews",
        "lang": "en",
        "style": "blog",
        "adsense": False,
        "category_id": 1,
        "keywords_file": "kw_oliveyoung.txt",
        "niche": "kbeauty",
    },
    {
        "url": "https://theseouljournal.com",
        "theme": "The Seoul Journal - Korea News & Expat Life",
        "lang": "en",
        "style": "magazine",
        "adsense": False,
        "category_id": 1,
        "keywords_file": "kw_seoul.txt",
        "niche": "culture",
    },
]
