from __future__ import annotations
import json, os, subprocess
from pathlib import Path

ROOT=Path(__file__).resolve().parents[1]
def load_env_file():
    p=Path(os.environ.get("YOUTUBE_ENV_FILE",""))
    if p.is_file():
        for raw in p.read_text(encoding="utf-8").splitlines():
            line=raw.strip()
            if not line or line.startswith("#") or "=" not in line:continue
            k,v=line.split("=",1); os.environ.setdefault(k.strip(),v.strip().strip('"').strip("'"))
def pick():
    data=json.loads((ROOT/"config/youtube_channels.json").read_text(encoding="utf-8"))
    for row in data["channels"]:
        prof=row["secret_profile"]
        if os.environ.get("YOUTUBE_OAUTH_REFRESH_TOKEN_"+prof):
            return row
    raise RuntimeError("no channel-specific refresh token found")
def main():
    load_env_file(); row=pick(); prof=row["secret_profile"]; key=row["channel_key"]
    out=ROOT/"artifacts"/"london-gpt-youtube-proof";out.mkdir(parents=True,exist_ok=True)
    video=out/"proof.mp4"
    subprocess.run(["ffmpeg","-y","-f","lavfi","-i","testsrc=size=1280x720:rate=24","-f","lavfi","-i","sine=frequency=440:sample_rate=44100","-t","8","-c:v","libx264","-pix_fmt","yuv420p","-c:a","aac",str(video)],check=True,stdout=subprocess.DEVNULL,stderr=subprocess.DEVNULL)
    from google.oauth2.credentials import Credentials
    from google.auth.transport.requests import Request
    from googleapiclient.discovery import build
    from googleapiclient.http import MediaFileUpload
    cid=os.environ.get("YOUTUBE_OAUTH_CLIENT_ID_"+prof) or os.environ.get("YOUTUBE_OAUTH_CLIENT_ID") or os.environ.get("YOUTUBE_OAUTH_CLIENT_ID_NEW")
    sec=os.environ.get("YOUTUBE_OAUTH_CLIENT_SECRET_"+prof) or os.environ.get("YOUTUBE_OAUTH_CLIENT_SECRET") or os.environ.get("YOUTUBE_OAUTH_CLIENT_SECRET_NEW")
    ref=os.environ["YOUTUBE_OAUTH_REFRESH_TOKEN_"+prof]
    creds=Credentials(token=None,refresh_token=ref,token_uri="https://oauth2.googleapis.com/token",client_id=cid,client_secret=sec,scopes=None);creds.refresh(Request())
    yt=build("youtube","v3",credentials=creds)
    actual=(yt.channels().list(part="id",mine=True,maxResults=1).execute().get("items") or [{}])[0].get("id","")
    if actual!=row["channel_id"]:raise RuntimeError(f"channel mismatch {actual} != {row['channel_id']}")
    title="LondonProjectGPT Private Upload Proof 2026-09-26"
    body={"snippet":{"title":title,"description":"Private system proof video generated by the LondonProjectGPT VPS pipeline. Not for public release.","categoryId":"27"},"status":{"privacyStatus":"private","selfDeclaredMadeForKids":False}}
    resp=yt.videos().insert(part="snippet,status",body=body,media_body=MediaFileUpload(str(video),mimetype="video/mp4",resumable=True)).execute()
    vid=resp["id"]
    check=yt.videos().list(part="snippet,status",id=vid).execute()["items"][0]
    result={"platform":"youtube","status":"uploaded","video_id":vid,"channel_key":key,"channel_id":check["snippet"]["channelId"],"privacy":check["status"]["privacyStatus"],"studio_url":f"https://studio.youtube.com/video/{vid}/edit"}
    (out/"receipt.json").write_text(json.dumps(result,ensure_ascii=False,indent=2),encoding="utf-8");print(json.dumps(result,ensure_ascii=False))
if __name__=="__main__":main()
