"""Resume only the 2026-09-07 failed Blogger batch on GitHub-hosted runners.

No model fallback. Completed sites are remembered; live queue records prevent
regeneration, and publication is delegated to the exact-job concurrency group.
"""
import json
import os
from pathlib import Path
import subprocess
import sys
from datetime import datetime, timedelta, timezone

ROOT=Path(__file__).resolve().parents[1]
sys.path[:0]=[str(ROOT),str(ROOT/'scripts')]
from gsheets_direct import get_sheets_service
from sync_automation_hub_to_sheets import QUEUE_TAB
import queue_blogger_rewrite

SITES=['jobglobal','kvisa365','kinvest365','oliveyoung','korea365','studyinkorea','koreanews',
       'korea_life_support365','kworld365','ktech365','koreawedding','kwellness_lab','kikorea',
       'kieca','ktrip365','ksa','kinsurance365','krealestate','seoul_intl_school_guide',
       'kfinance365','jobkorea365','kmedical_job_center','medicaltour','khealth365','kskin365','kstudy365',
       'kworld365_kpop','koreataxlaw']
WEDDING_DESCRIPTION="Baek Jin-hee's 2027 wedding: practical notes for international couples on privacy and cross-cultural ceremonies."
REPAIR_DESCRIPTIONS={
 'blogger-5edda9f3eb9099408391':WEDDING_DESCRIPTION,
 'blogger-808d86cff4c4e6989be8':"Travel deals: target 9.9 sale fares, Korea wellness packages, and low-cost hotels with a practical booking checklist."
}
STATE_PATH='data/blogger-recovery-2026-09-07.json' 

def gh(*args):
    return subprocess.check_output(['gh',*args],text=True,encoding='utf-8').strip()

def rows(service):
    data=service.spreadsheets().values().get(spreadsheetId=os.environ['SHEET_ID'],range=f"'{QUEUE_TAB}'!A1:N").execute().get('values',[])
    return [dict(zip(data[0],row+['']*len(data[0]))) for row in data[1:]] if data else []

def main():
    import base64
    repository=os.environ['GITHUB_REPOSITORY']
    endpoint=f'repos/{repository}/contents/{STATE_PATH}'
    response=subprocess.run(['gh','api',endpoint],capture_output=True,text=True,encoding='utf-8')
    if response.returncode:
        if '404' not in response.stderr:
            raise RuntimeError('Cannot read recovery state')
        state={'completed':{},'next_generation_after':''};sha=None
    else:
        obj=json.loads(response.stdout);sha=obj['sha'];state=json.loads(base64.b64decode(obj['content']))
    service=get_sheets_service()
    now=datetime.now(timezone.utc)
    generation_allowed=not state.get('next_generation_after') or now>=datetime.fromisoformat(state['next_generation_after']) or os.getenv('FORCE_RETRY')=='true'
    report=[];generated=0
    profiles=json.loads((ROOT/'config/content_engine_profiles.json').read_text(encoding='utf-8'))['profiles']
    for key in SITES:
        site='blogger_'+key
        if site in state['completed']:
            report.append({'site':site,'status':'published','public_url':state['completed'][site]});continue
        queue=rows(service)
        current=[r for r in queue if r.get('site_id')==site and r.get('created_at','').startswith('2026-09-07')]
        # On later days include exactly the jobs generated by this recovery.
        tracked=state.get('jobs',{}).get(site)
        current += [r for r in queue if tracked and r.get('job_id')==tracked and r not in current]
        published=next((r for r in current if r.get('status')=='published' and r.get('public_url')),None)
        if published:
            state['completed'][site]=published['public_url'];report.append({'site':site,'status':'published','public_url':published['public_url']});continue
        pending=next((r for r in current if r.get('status') in {'ready','processing','drafted','verification_failed'} and r.get('title')),None)
        invalid=next((r for r in current if r.get('job_id') in REPAIR_DESCRIPTIONS and r.get('error_code')=='invalid_job'),None)
        if pending or invalid:
            item=pending or invalid
            if item.get('status')=='ready' or invalid:
                args=['workflow','run','platform-publish-v2.yml','--repo',repository,'--ref','main','-f','platform=blogger','-f','job_id='+item['job_id'],'-f','max_jobs=1']
                if invalid:args+=['-f','recover_invalid_job=true','-f','recovery_search_description='+REPAIR_DESCRIPTIONS[item['job_id']]]
                gh(*args)
            report.append({'site':site,'status':'existing_job','job_id':item['job_id']});continue
        if not generation_allowed or generated>=3:
            report.append({'site':site,'status':'awaiting_generation'});continue
        profile=next((p for p in profiles if p['site_key']==key),None)
        if not profile:
            report.append({'site':site,'status':'missing_profile'});continue
        out=ROOT/'recovery-job-output.txt';out.write_text('')
        os.environ.update({'BLOGGER_SITE_ID':site,'BLOGGER_LANGUAGE':profile.get('language','en'),
            'BLOGGER_PERSONA':profile.get('blogspot',{}).get('persona','specialist editor'),
            'BLOGGER_TONE':profile.get('blogspot',{}).get('tone','Practical and precise'),
            'BLOGGER_TARGET_CHARS':'1800','BLOGGER_PUBLISH_NOW':'true','BLOGGER_RECOVER_FROM_WP':'true' if profile.get('wordpress',{}).get('url') else 'false',
            'SOURCE_WP_URL':'','BLOGGER_FORCE_KEYWORD':'','GITHUB_OUTPUT':str(out)})
        try:
            generated+=1
            queue_blogger_rewrite.main()
            job=next((line.split('=',1)[1] for line in out.read_text().splitlines() if line.startswith('job_id=')),None)
            if job:
                state.setdefault('jobs',{})[site]=job
                gh('workflow','run','platform-publish-v2.yml','--repo',repository,'--ref','main','-f','platform=blogger','-f','job_id='+job,'-f','max_jobs=1')
                report.append({'site':site,'status':'dispatched','job_id':job})
            else:report.append({'site':site,'status':'no_new_source'})
        except (Exception,SystemExit) as error:
            message=str(error)
            # Never persist request URLs or secrets from provider exceptions.
            reason='GEMINI_QUOTA' if 'GEMINI_QUOTA' in message else type(error).__name__
            report.append({'site':site,'status':'blocked','reason':reason})
            if reason=='GEMINI_QUOTA':
                generation_allowed=False
                state['next_generation_after']=(now+timedelta(hours=6)).isoformat()
    state['checked_at']=now.isoformat();state['results']=report
    Path('artifacts').mkdir(exist_ok=True)
    Path('artifacts/blogger-recovery.json').write_text(json.dumps(state,ensure_ascii=False,indent=2),encoding='utf-8')
    payload={'message':'chore: Blogger recovery progress [skip ci]','branch':'main','content':base64.b64encode(json.dumps(state,ensure_ascii=False,indent=2).encode()).decode()}
    if sha:payload['sha']=sha
    subprocess.run(['gh','api',endpoint,'--method','PUT','--input','-'],input=json.dumps(payload),text=True,encoding='utf-8',capture_output=True,check=True)
    print(json.dumps(report,ensure_ascii=False))
    if all('blogger_'+key in state['completed'] for key in SITES):
        gh('workflow','disable','blogger-failure-recovery.yml','--repo',repository)
if __name__=='__main__':main()
