"""Canonical registry for the 27-site network."""
SITES = [
    ("https://k-health365.com", "KHEALTH365COM", "priority"),
    ("https://koreamedicaltour.com", "KOREAMEDICALTOURCOM", "active"),
    ("https://koreainvest365.com", "KOREAINVEST365COM", "active"),
    ("https://ki-korea.com", "KIKOREACOM", "active"),
    ("https://koreainsurance365.com", "KOREAINSURANCE365COM", "active"),
    ("https://kfinance365.com", "KFINANCE365COM", "active"),
    ("https://koreataxnlaw.com", "KOREATAXNLAWCOM", "active"),
    ("https://koreacrypto365.com", "KOREACRYPTO365COM", "active"),
    ("https://krealestate365.com", "KREALESTATE365COM", "active"),
    ("https://ktech365.com", "KTECH365COM", "active"),
    ("https://kskin365.com", "KSKIN365COM", "active"),
    ("https://oliveyoungkorea.com", "OLIVEYOUNGKOREACOM", "active"),
    ("https://kworld365.com", "KWORLD365COM", "active"),
    ("https://k-trip365.com", "KTRIP365COM", "active"),
    ("https://k-visa365.com", "KVISA365COM", "active"),
    ("https://koreawedding365.com", "KOREAWEDDING365COM", "active"),
    ("https://kstudy365.com", "KSTUDY365COM", "active"),
    ("https://studyinkorea365.com", "STUDYINKOREA365COM", "active"),
    ("https://kieca-korea.org", "KIECAKOREAORG", "active"),
    ("https://ksa-korea.org", "KSAKOREAORG", "active"),
    ("https://sis-korea.com", "SISKOREACOM", "active"),
    ("https://jobkorea365.com", "JOBKOREA365COM", "active"),
    ("https://jobinkorea365.com", "JOBINKOREA365COM", "active"),
    ("https://jobkoreaglobal.com", "JOBKOREAGLOBALCOM", "review"),
    ("https://korea365.org", "KOREA365ORG", "active"),
    ("https://koreanews365.com", "KOREANEWS365COM", "active"),
    ("https://theseouljournal.com", "THESEOULJOURNALCOM", "active"),
]
ACTIVE_SITES = [row for row in SITES if row[2] != "retired"]
